name: Docker Image
on: 
  push:
    tags:
      - '**'
    branches:
      - main
  pull_request:
    paths: 
      - .github/workflows/dockerimage.yml
      - build.sh
      - Dockerfile
      - protoc-wrapper
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ./build.sh -t build
    - name: Push the Docker image
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        function tag_and_push {
          docker tag build "unkeep/protoc:${1}" && docker push "unkeep/protoc:${1}"
        }

        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          tag_and_push "development"
        elif [[ "${GITHUB_REF}" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            TAG="${GITHUB_REF#"refs/tags/v"}"
            tag_and_push "${TAG}"
            if [[ "${TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then 
                tag_and_push "${TAG%.*}"
                tag_and_push "${TAG%.*.*}"; 
                tag_and_push "latest"
            fi
        else
          tag_and_push "${GITHUB_REF#"refs/tags/"}"
        fi
